# Generated by Django 5.2.2 on 2025-06-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userauth_address_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
