# Generated by Django 5.2.3 on 2025-06-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userauth_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauth',
            name='default_address',
        ),
        migrations.AddField(
            model_name='userauth',
            name='shop_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
