# Generated by Django 5.2.4 on 2025-08-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='BDM', max_length=100)),
                ('logo', models.ImageField(default='logos/logo.png', upload_to='logos/')),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('description', models.TextField(default='A platform for managing orders.')),
                ('delivery_charge', models.DecimalField(decimal_places=1, default=80.0, max_digits=10)),
                ('contact_email', models.EmailField(default='info@bdm.com', max_length=254)),
                ('contact_phone', models.CharField(default='1234567890', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
