# Generated by Django 5.2.4 on 2025-08-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfomodel',
            name='logo',
            field=models.ImageField(default='logos/logo.png', upload_to='logos/'),
        ),
    ]
