# Generated by Django 5.2.3 on 2025-06-13 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.CharField(default=datetime.datetime(2025, 6, 13, 14, 4, 18, 411042, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
