# Generated by Django 5.2.2 on 2025-06-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='product',
            name='regular_price',
        ),
    ]
