# Generated by Django 5.2.4 on 2025-08-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='generic_name',
            new_name='generic_id',
        ),
    ]
