# Generated by Django 5.2.2 on 2025-06-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_base_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='base_price',
            new_name='cost_price',
        ),
    ]
