# Generated by Django 5.2.2 on 2025-06-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_base_price_product_cost_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='company',
            new_name='company_id',
        ),
    ]
