# Generated by Django 5.2.2 on 2025-06-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_category_product_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='products.company'),
        ),
    ]
