# Generated by Django 5.2.4 on 2025-07-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_selling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='generic_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
