# Generated by Django 5.2.4 on 2025-07-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_generic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='generic_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
