# Generated by Django 5.2.4 on 2025-07-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_generic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_per_box',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
