# Generated by Django 5.2.4 on 2025-08-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_quantity_per_box'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('banner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='banner_images')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
