# Generated by Django 5.2.4 on 2025-08-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_bannerimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericName',
            fields=[
                ('generic_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Generic Name',
                'ordering': ['name'],
            },
        ),
    ]
